name: build

on:
  push:
    branches: [ Custom ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  LM_LICENSE_FILE: "${{ github.workspace }}/tools/cw/license.dat"
  BUILD: /var/tmp/pokeplatinum

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Install Software
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends bison flex g++ gcc-arm-none-eabi git make ninja-build pkg-config python3 wget xz-utils libpng-dev

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Install Metroskrew
        run: sudo make skrew

      - name: Configure Repo
        run: make configure

      - name: Compile ROM
        run: make rom

      - name: Find built ROM
        run: |
          find "$BUILD" -type f -name '*.nds' -print
          find "${{ github.workspace }}" -type f -name '*.nds' -print

      - name: Upload ROM
        uses: actions/upload-artifact@v7
        with:
          name: pokeplatinum-rom
          path: /var/tmp/pokeplatinum/**/*.nds
          if-no-files-found: error
          retention-days: 90
